micronaut:
  application:
    name: restapi
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: site-2021-ada-web2-tarlan-ismayilsoy